name: Laravel and React CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP extensions for MongoDB
        run: |
          sudo apt-get install -y libssl-dev
          sudo pecl install mongodb
          echo "extension=mongodb.so" | sudo tee -a $(php -r "echo php_ini_loaded_file();")

      - name: Install Composer Dependencies
        run: composer install

      - name: Setup Laravel Environment (using secrets)
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Laravel Migrations
        run: php artisan migrate --no-interaction

      # Frontend setup
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install npm dependencies
        run: npm install

      - name: Build React App
        run: npm run build
